//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entameen1
    {
        public int id { get; set; }
        public string E_Name { get; set; }
        public string Pass { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Addresso { get; set; }
    }
}
